using System.Text;

namespace FactVaultManager.Desktop;

public static class QuizVisualExportRewriter
{
    public static QuizVideoBuildResult ReExport(
        QuizVideoBuildResult build,
        IReadOnlyList<QuizQuestion> questions,
        QuizVideoBuildOptions options)
    {
        ArgumentNullException.ThrowIfNull(build);
        ArgumentNullException.ThrowIfNull(questions);
        ArgumentNullException.ThrowIfNull(options);
        options.Validate();
        build.Timeline.Validate();

        QuizTimelineEndTrimmer.TrimToVideoEnd(build.Timeline);
        var finalized = QuizExportProjectFinalizer.Prepare(build);
        var metadata = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["title"] = options.Title,
            ["description"] = $"{questions.Count}-question quiz generated by FactVaultManager.",
            ["script"] = BuildTextScript(questions),
            ["sources"] = "Quiz question bank",
        };
        var resolve = new NativeResolveFreeExportService().Export(
            build.Timeline,
            finalized.ProjectFolder,
            metadata,
            strict: true,
            overwrite: true);

        return new QuizVideoBuildResult(
            finalized.ProjectFolder,
            finalized.QuizJson,
            build.Timeline,
            resolve);
    }

    private static string BuildTextScript(IReadOnlyList<QuizQuestion> questions)
    {
        var builder = new StringBuilder();
        for (var index = 0; index < questions.Count; index++)
        {
            var question = questions[index];
            builder.AppendLine($"Question {index + 1}: {question.Question}");
            for (var answer = 0; answer < question.Answers.Count; answer++)
                builder.AppendLine($"{(char)('A' + answer)}. {question.Answers[answer]}");
            builder.AppendLine($"Correct: {question.CorrectLetter}. {question.CorrectAnswer}");
            if (!string.IsNullOrWhiteSpace(question.Explanation))
                builder.AppendLine(question.Explanation);
            builder.AppendLine();
        }
        return builder.ToString().Trim();
    }
}

public static class QuizTimelineEndTrimmer
{
    public static double TrimToVideoEnd(NativeTimeline timeline)
    {
        ArgumentNullException.ThrowIfNull(timeline);
        timeline.Validate();

        var videoEnd = timeline.Tracks
            .Where(track => track.Kind == NativeTimelineTrackKind.Video)
            .SelectMany(track => track.Clips)
            .Where(clip => clip.Kind is NativeTimelineClipKind.Image or NativeTimelineClipKind.Video)
            .Select(clip => clip.End)
            .DefaultIfEmpty(0)
            .Max();
        if (videoEnd <= 0)
            throw new InvalidOperationException("Quiz timeline has no video cards to export.");

        foreach (var track in timeline.Tracks.Where(track => track.Kind != NativeTimelineTrackKind.Video))
        {
            track.Clips.RemoveAll(clip => clip.Start >= videoEnd);
            foreach (var clip in track.Clips.Where(clip => clip.End > videoEnd))
                clip.Duration = videoEnd - clip.Start;
        }

        timeline.Scenes.RemoveAll(scene => scene.Start >= videoEnd);
        foreach (var scene in timeline.Scenes.Where(scene => scene.End > videoEnd))
            scene.Duration = videoEnd - scene.Start;

        timeline.Validate();
        return videoEnd;
    }
}
