using System.Text;

namespace FactVaultManager.Desktop;

public static class QuizVisualExportRewriter
{
    public static QuizVideoBuildResult ReExport(
        QuizVideoBuildResult build,
        IReadOnlyList<QuizQuestion> questions,
        QuizVideoBuildOptions options)
    {
        ArgumentNullException.ThrowIfNull(build);
        ArgumentNullException.ThrowIfNull(questions);
        ArgumentNullException.ThrowIfNull(options);
        options.Validate();
        build.Timeline.Validate();

        var finalized = QuizExportProjectFinalizer.Prepare(build);
        var metadata = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["title"] = options.Title,
            ["description"] = $"{questions.Count}-question quiz generated by FactVaultManager.",
            ["script"] = BuildTextScript(questions),
            ["sources"] = "Quiz question bank",
        };
        var resolve = new NativeResolveFreeExportService().Export(
            build.Timeline,
            finalized.ProjectFolder,
            metadata,
            strict: true,
            overwrite: true);

        return new QuizVideoBuildResult(
            finalized.ProjectFolder,
            finalized.QuizJson,
            build.Timeline,
            resolve);
    }

    private static string BuildTextScript(IReadOnlyList<QuizQuestion> questions)
    {
        var builder = new StringBuilder();
        for (var index = 0; index < questions.Count; index++)
        {
            var question = questions[index];
            builder.AppendLine($"Question {index + 1}: {question.Question}");
            for (var answer = 0; answer < question.Answers.Count; answer++)
                builder.AppendLine($"{(char)('A' + answer)}. {question.Answers[answer]}");
            builder.AppendLine($"Correct: {question.CorrectLetter}. {question.CorrectAnswer}");
            if (!string.IsNullOrWhiteSpace(question.Explanation))
                builder.AppendLine(question.Explanation);
            builder.AppendLine();
        }
        return builder.ToString().Trim();
    }
}
