using System.Text;
using System.Xml.Linq;

namespace FactVaultManager.Desktop;

public static class QuizVisualExportRewriter
{
    public static QuizVideoBuildResult ReExport(
        QuizVideoBuildResult build,
        IReadOnlyList<QuizQuestion> questions,
        QuizVideoBuildOptions options)
    {
        ArgumentNullException.ThrowIfNull(build);
        ArgumentNullException.ThrowIfNull(questions);
        ArgumentNullException.ThrowIfNull(options);
        options.Validate();
        build.Timeline.Validate();

        QuizOpeningSequence.RenderAndApply(build.Timeline, build.ProjectFolder, options);
        QuizFullCountdownRewriter.Apply(build.Timeline, questions, build.ProjectFolder, options);
        QuizTimelineEndTrimmer.TrimToVideoEnd(build.Timeline);
        QuizAnimatedBackground.RenderAndApply(build.Timeline, build.ProjectFolder);
        var finalized = QuizExportProjectFinalizer.Prepare(build);
        var metadata = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["title"] = options.Title,
            ["description"] = $"{questions.Count}-question quiz generated by FactVaultManager.",
            ["script"] = BuildTextScript(questions),
            ["sources"] = "Quiz question bank",
        };
        var resolve = new NativeResolveFreeExportService().Export(
            build.Timeline,
            finalized.ProjectFolder,
            metadata,
            strict: true,
            overwrite: true);
        QuizFcpXmlTimelineSynchronizer.AlignToTimeline(resolve, build.Timeline);

        return new QuizVideoBuildResult(
            finalized.ProjectFolder,
            finalized.QuizJson,
            build.Timeline,
            resolve);
    }

    private static string BuildTextScript(IReadOnlyList<QuizQuestion> questions)
    {
        var builder = new StringBuilder();
        for (var index = 0; index < questions.Count; index++)
        {
            var question = questions[index];
            builder.AppendLine($"Question {index + 1}: {question.Question}");
            for (var answer = 0; answer < question.Answers.Count; answer++)
                builder.AppendLine($"{(char)('A' + answer)}. {question.Answers[answer]}");
            builder.AppendLine($"Correct: {question.CorrectLetter}. {question.CorrectAnswer}");
            if (!string.IsNullOrWhiteSpace(question.Explanation))
                builder.AppendLine(question.Explanation);
            builder.AppendLine();
        }
        return builder.ToString().Trim();
    }
}

public static class QuizFcpXmlTimelineSynchronizer
{
    public const string AudioGainAmount = "4dB";

    public static void AlignToTimeline(NativeResolveFreeExportResult resolve, NativeTimeline timeline)
    {
        ArgumentNullException.ThrowIfNull(resolve);
        ArgumentNullException.ThrowIfNull(timeline);
        timeline.Validate();

        var document = XDocument.Load(resolve.FcpXml.Path);
        var resources = document.Root?.Element("resources")
            ?? throw new NativeResolveExportException("Quiz FCPXML is missing its resources section.");
        var sequence = document.Root?.Element("library")?.Element("event")?.Element("project")?.Element("sequence")
            ?? throw new NativeResolveExportException("Quiz FCPXML is missing its sequence.");
        var spine = sequence.Element("spine")
            ?? throw new NativeResolveExportException("Quiz FCPXML is missing its spine.");

        var assetIds = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var asset in resources.Elements("asset"))
        {
            var id = ((string?)asset.Attribute("id") ?? "").Trim();
            var source = ((string?)asset.Elements("media-rep")
                .FirstOrDefault(element => string.Equals(
                    (string?)element.Attribute("kind"),
                    "original-media",
                    StringComparison.OrdinalIgnoreCase))
                ?.Attribute("src") ?? "").Trim();
            if (id.Length == 0 || source.Length == 0 ||
                !Uri.TryCreate(source, UriKind.Absolute, out var uri) || !uri.IsFile)
                continue;
            assetIds[Path.GetFullPath(uri.LocalPath)] = id;
        }

        var parent = new XElement("gap",
            new XAttribute("name", "Quiz Timeline"),
            new XAttribute("offset", "0s"),
            new XAttribute("start", "0s"),
            new XAttribute("duration", Time(timeline.Duration, timeline.FrameRate)));

        var videoLane = 1;
        foreach (var track in timeline.Tracks.Where(track => track.Kind == NativeTimelineTrackKind.Video))
        {
            foreach (var clip in track.Clips
                         .Where(clip => clip.Kind is NativeTimelineClipKind.Image or NativeTimelineClipKind.Video)
                         .OrderBy(clip => clip.Start))
            {
                parent.Add(BuildConnectedClip(resolve, clip, assetIds, timeline.FrameRate, videoLane));
            }
            videoLane++;
        }

        var audioLane = -1;
        foreach (var track in timeline.Tracks.Where(track => track.Kind == NativeTimelineTrackKind.Audio))
        {
            foreach (var clip in track.Clips
                         .Where(clip => clip.Kind == NativeTimelineClipKind.Audio)
                         .OrderBy(clip => clip.Start))
            {
                parent.Add(BuildConnectedClip(resolve, clip, assetIds, timeline.FrameRate, audioLane));
            }
            audioLane--;
        }

        spine.ReplaceNodes(parent);
        sequence.SetAttributeValue("duration", Time(timeline.Duration, timeline.FrameRate));
        document.Save(resolve.FcpXml.Path, SaveOptions.None);

        NativeFcpXmlExporter.ValidateMedia(
            resolve.FcpXml.Path,
            resolve.Package.PackageFolder,
            resolve.ValidatedMedia);
    }

    private static XElement BuildConnectedClip(
        NativeResolveFreeExportResult resolve,
        NativeTimelineClip clip,
        IReadOnlyDictionary<string, string> assetIds,
        double frameRate,
        int lane)
    {
        if (string.IsNullOrWhiteSpace(clip.Source))
            throw new NativeResolveExportException($"Quiz clip has no source: {clip.Id}");

        var original = Path.GetFullPath(clip.Source);
        if (!resolve.Package.SourceMap.TryGetValue(original, out var copied))
            throw new NativeResolveExportException($"Quiz media is missing from the portable package: {original}");
        copied = Path.GetFullPath(copied);
        if (!assetIds.TryGetValue(copied, out var assetId))
            throw new NativeResolveExportException($"Quiz FCPXML asset was not found for: {copied}");

        var connectedClip = new XElement("asset-clip",
            new XAttribute("name", string.IsNullOrWhiteSpace(clip.Name) ? Path.GetFileName(original) : clip.Name),
            new XAttribute("ref", assetId),
            new XAttribute("offset", Time(clip.Start, frameRate)),
            new XAttribute("start", Time(clip.SourceIn, frameRate)),
            new XAttribute("duration", Time(clip.Duration, frameRate)),
            new XAttribute("lane", lane));
        if (clip.Kind == NativeTimelineClipKind.Audio)
        {
            connectedClip.Add(new XElement("adjust-volume",
                new XAttribute("amount", AudioGainAmount)));
        }
        return connectedClip;
    }

    private static string Time(double seconds, double frameRate)
    {
        var frames = Math.Max(0, (int)Math.Round(seconds * frameRate, MidpointRounding.ToEven));
        var denominator = Math.Max(1, (int)Math.Round(frameRate, MidpointRounding.ToEven));
        return $"{frames}/{denominator}s";
    }
}

public static class QuizTimelineEndTrimmer
{
    public static double TrimToVideoEnd(NativeTimeline timeline)
    {
        ArgumentNullException.ThrowIfNull(timeline);
        timeline.Validate();

        var videoEnd = timeline.Tracks
            .Where(track => track.Kind == NativeTimelineTrackKind.Video)
            .SelectMany(track => track.Clips)
            .Where(clip => clip.Kind is NativeTimelineClipKind.Image or NativeTimelineClipKind.Video)
            .Select(clip => clip.End)
            .DefaultIfEmpty(0)
            .Max();
        if (videoEnd <= 0)
            throw new InvalidOperationException("Quiz timeline has no video cards to export.");

        foreach (var track in timeline.Tracks.Where(track => track.Kind != NativeTimelineTrackKind.Video))
        {
            track.Clips.RemoveAll(clip => clip.Start >= videoEnd);
            foreach (var clip in track.Clips.Where(clip => clip.End > videoEnd))
                clip.Duration = videoEnd - clip.Start;
        }

        timeline.Scenes.RemoveAll(scene => scene.Start >= videoEnd);
        foreach (var scene in timeline.Scenes.Where(scene => scene.End > videoEnd))
            scene.Duration = videoEnd - scene.Start;

        timeline.Validate();
        return videoEnd;
    }
}
